apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-example
  labels:
    app: log-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-example
  template:
    metadata:
      labels:
        app: log-example
    spec:
      containers:
      - name: go-backend
        image: lyzhang1999/log-example:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe: 
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe: 
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: log-example
  labels:
    app: log-example
spec:
  type: ClusterIP
  selector:
    app: log-example
  ports:
  - port: 8080
    targetPort: 8080